services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
    user: "${UID:-1000}:${GID:-1000}"
    command: >
      bash -c "python init_db.py &&
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
